/**
 * GuardController is the extension point for guard decision logic.
 * Ahmed can implement FSM/BT variants by extending this class.
 */
export class GuardController {
  constructor() {
    if (new.target === GuardController) {
      throw new Error("Cannot instantiate abstract GuardController directly.");
    }
  }

  /**
   * Called once when the guard is created or assigned a new controller.
   */
  onAttach(_guard) {}

  /**
   * Called every frame from Guard.updateBehaviour.
   * The runtime context is generated by World and contains game references.
   */
  update(_dt, _guard, _runtimeContext) {}
}
